name: build and release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-and-release:
    name: Release on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            sys_name: linux
          - os: windows-latest
            sys_name: windows
          - os: macos-latest
            sys_name: macos

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update && sudo apt-get install -y libsdl2-dev zenity

      - name: Install Dependencies (macOS)
        if: runner.os == 'macOS'
        run: brew install sdl2

      - name: Setup MSYS2 (Windows)
        if: runner.os  == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >-
            mingw-w64-ucrt-x86_64-gcc
            mingw-w64-ucrt-x86_64-cmake
            mingw-w64-ucrt-x86_64-make
            mingw-w64-ucrt-x86_64-SDL2

      - name: Configure and Build (Unix)
        if: runner.os != 'Windows'
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release
      - name: Configure and Build (Windows)
        if: runner.os == 'Windows'
        shell: msys2 {0}
        run: |
          cmake -S . -B build -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release

      - name: Package with CPack
        shell: bash
        run: |
          cd build
          cpack -G ZIP
          mv CHIP-8-Emulator-*.zip chip8-emulator-${{ matrix.sys_name }}.zip

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/chip8-emulator-${{ matrix.sys_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
